### ISSUE TITLE
broken in ansible 1.7

### ISSUE THREAD

**Issue by sebastianneubauer** [eggsby/ansible-supervisor#4]
Unfortunately there were quite some changes in ansible. While these playbooks (supervisor, supervise) works with ansible 1.6.6 they doesn't work with 1.7. 
This seems to be the related ansible issue:
https://github.com/ansible/ansible/issues/8233

**Comment by vohof** [comment]
Hi, any updates?

**Comment by eggsby** [comment]
Thank you for the reminder @vohof - I'd been sitting on this patch for a while now.

Fixed and released the latest to ansible galaxy.

The only important difference is that `{{ super_args }}` is no longer supported due to changes mentioned in the bug @sebastianneubauer linked.

Instead, you can use `supervisorctl_path: ~/bin/supervisorctl`

Thanks again for bringing this up,
Thomas
